name: assistantapp
description: Assistente vocale Android-first
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vosk_flutter_service: ^0.1.0
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  nfc_manager: ^4.1.1
  sensors_plus: ^4.0.2
  camera: ^0.11.0+2
  google_mlkit_object_detection: ^0.12.0
  
dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/vosk-model-small-it-0.22/
    - assets/models/vosk-model-small-it-0.22.zip
    
    
